PhaniResume/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhaniResume.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PhaniResume/Controllers/PhaniResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceLayer.Services;

namespace PhaniResume.Controllers
{
    public class PhaniResumeController : Controller
    {
        private readonly IResumeService _resumeService;

        public PhaniResumeController(IResumeService resumeService)
        {
            _resumeService = resumeService;
        }


        // GET: PhaniResume
        public ActionResult GetCustomerDetails()
        {
            var s = _resumeService.GetcustomerByCustomer(1);
            return View("CustomerDetails",s);
        }

        public ActionResult GetResumeDetailsSummary(int customerId)
        {
            var s = _resumeService.GetcustomerByCustomer(customerId);
            return PartialView("GetResumeDetailsSummary", s);
        }

        public ActionResult GetNewResume(int customerId)
        {
            var s = _resumeService.GetcustomerByCustomer(customerId);
            return PartialView("GetResumeDetailsSummary", s);
        }
    }
}

PhaniResume/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

<p> Sample Azure.</p>

PhaniResume/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhaniResume/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PhaniResume/Views/PhaniResume/CustomerDetails.cshtml
@model webapi.proxies.Models.CustomerDetail
<div id="CustomerDetails" class="panel panel-success mvc-form">
    <div class="panel-heading">
        <div >
            <h3 class="panel-title">
                Applicant Personal Details
            </h3>
        </div>
    </div>
    <div class="panel-body mvc-element panel-collapse in" id="CustomerDetailsbody">
        <div class="form-group">
            <div class="form-group row">
                <label class="col-sm-2">First Name </label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x=>x.FirstName , new {@class= "form-control"})
                </div>
            </div>
            
            <div class="form-group row">
                <label class="col-sm-2"> Last Name</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
                </div>
            </div>
            
            <div class="form-group row">
                <label class="col-sm-2"> phone Number</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.phoneNumber, new { @class = "form-control" , type = "number"})
                </div>
            </div>
            
            <div class="form-group row">
                <label class="col-sm-2">Zipcode</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(x => x.Zipcode, new { @class = "form-control", type = "number" })
                </div>
            </div>
        </div>
        
        <div id="Resume-Details-Summary"></div>

    </div>
</div>


@section scripts {
    <script>
        $(function() {
            ResumeDetials.init({
                customerId: 1 ,
                applicationPath :"@Request.ApplicationPath"
            });
        });
    </script>

}

PhaniResume/Views/PhaniResume/GetResumeDetailsSummary.cshtml
@model webapi.proxies.Models.CustomerDetail

<style>
    .dataTables_paginate {
        display: none;
    }
</style>
<div id="ResumeDetailSummaryDiv" class="panel panel-success mvc-form">
    
    <div class="panel-heading">
        <div style="float: left; margin-top:5px;">
            <h3 class="panel-title">
                Resume Summary
            </h3>

        </div>
        <div style="float: right">
            <a id="AddNewResume" data-image-id="@Model.CustomerDetailsID" class="btn btn-success">      Add Resume </a>
        </div>

        <div style="clear: both"> </div>
    </div>
    <div class="panel-body mvc-element panel-collapse collapse in" id="ResumeDetailsSummarypanelBody" print-toggle>
        <table id="Resume-Details-Summary-Table" class="table table-condensed table-hover table-striped" cellspacing="0" style="border-width: 0; width: 100%;border-collapse: collapse"> 
            @if (!Model.ResumeDetails.Any())
            {
                <tbody>
                <tr class="GridEmptyDataTemplate">
                    <td colspan="4">
                        <div class="GridEmptyDataTemplate">
                            No Resume Found
                        </div>
                    </td>
                </tr>
                </tbody>
            }
            else
            {
                <thead>
                <tr class="table-header">
                    <th style="width: 20px;"></th>
                    <th scope="col">Resume ID </th>
                    <th scope="col"> Carrier Objective </th>
                    <th scope="col"> Honors</th>
                </tr>
                </thead>
                <tfoot >
                <tr class="table-footer">
                    <th colspan="4">
                        <div class="row footer-div">
                            <div class="col-sm-5">
                                <a class="pagining previous btn btn-success btn-xs"> previous</a>
                                <a class="pagining next btn btn-success btn-xs"> Next</a>
                                <span class="SelectionHeader " style="margin-left: 10px; position: relative;"> Go to Page</span>
                                <input type="text" value="1" class="form-control inlineBlock go-to-pagining-input editFieldGrid" style="width: 30px;" />
                                <a class="go-to-pagining btn btn-success btn-xs">GO</a>
                            </div>
                        </div>
                    </th>

                </tr>

                </tfoot>
                <tbody>
                @{
                    foreach (var resume in Model.ResumeDetails)
                    {
                        <tr>
                            <td> <span style="margin-right: 10px;" class="fa fa-trash-o fa-2x delete-resume" data-resume-detail-id="@resume.ResumeDetailsId" aria-hidden="true"> </span></td>
                            <td> @resume.ResumeDetailsId</td>
                            <td> @resume.CAREER_OBJECTIVE</td>
                            <td> @resume.HONORS_AND_REWARDS</td>
                        </tr>
                    }
                }
                </tbody>
            }
        </table>
    </div>
</div>

<script>
    $(function() {

        ResumeDetials.loadCollectiionPasswordEvents({
            DeleteResumeURL: "@Html.Raw(Url.Action("GetCustomerDetails","PhaniResume"))",
            AddResumeURL: ""

        });

        site.makeDataTable("#Resume-Details-Summary-Table");

    })
</script>

PhaniResume/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Resume Details", "GetCustomerDetails", "PhaniResume")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    <br/>
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/DataTables")
@Scripts.Render("~/bundles/MVC")

    @RenderSection("scripts", required: false)
</body>
</html>